### ISSUE TITLE
module compatibility

### ISSUE THREAD

**Issue by r-liciotti** [wfpaisa/blockwishlist#1]
the module is compatible with version 1.7 ? Because i can' t install it.

**Comment by wfpaisa** [comment]
what is it your error message?

**Comment by r-liciotti** [comment]
PS can t see it. Doesnt see in ftp and with normal installation.  (1.7.3 version)

**Comment by wfpaisa** [comment]
Try to do:

1. Download de project.
2. Unzip in a folder and call it: `blockwishlist`
3. Put in `/modules/` folder
4. Go to Admin Prestashop / modules and find it and install

**Comment by r-liciotti** [comment]
Thank you, now works.
